In [2]:
import numpy as np
n1 = np.array([1,2,3,8,9,10])
n2 = np.array([4,5,6,8,9,10])


In [3]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6,  8,  9, 10]])

In [4]:
np.hstack((n1,n2))

array([ 1,  2,  3,  8,  9, 10,  4,  5,  6,  8,  9, 10])

In [5]:
np.column_stack((n1,n2))

array([[ 1,  4],
       [ 2,  5],
       [ 3,  6],
       [ 8,  8],
       [ 9,  9],
       [10, 10]])

In [6]:
np.intersect1d(n1,n2)

array([ 8,  9, 10])

In [7]:
np.setdiff1d(n1,n2)

array([1, 2, 3])

In [8]:
np.setdiff1d(n2,n1)

array([4, 5, 6])

In [9]:
np.sum([n1,n2])

np.int64(75)

In [10]:
np.sum([n1,n2],axis=0)

array([ 5,  7,  9, 16, 18, 20])

In [11]:
np.sum([n1,n2],axis=1)

array([33, 42])

In [12]:
n1=n1+1

In [13]:
print(n1)

[ 2  3  4  9 10 11]


In [14]:
n1

array([ 2,  3,  4,  9, 10, 11])

In [15]:
n1=n1/4

In [16]:
n1

array([0.5 , 0.75, 1.  , 2.25, 2.5 , 2.75])

In [17]:
n1=n1*100
n1

array([ 50.,  75., 100., 225., 250., 275.])

In [18]:
np.mean(n1)


np.float64(162.5)

In [19]:
np.median(n1)


np.float64(162.5)

In [20]:
np.std(n1)

np.float64(89.8494110535326)

In [21]:
np.save("my_numpyarray",n1)

In [22]:
n3=np.load("my_numpyarray.npy")
n3

array([ 50.,  75., 100., 225., 250., 275.])

In [23]:
n1+n2

array([ 54.,  80., 106., 233., 259., 285.])

In [24]:
n1.shape

(6,)

In [25]:
n2.shape

(6,)

In [26]:
n5=np.array([1,2,3])
n5.shape=(1,3)
n5

array([[1, 2, 3]])

In [27]:
n6=np.array([2,4,6])
n6.shape=(3,1)
n6

array([[2],
       [4],
       [6]])

In [28]:
n5+n6

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [29]:
n7=np.array([[1,2,2],[3,3,3],[4,4,4]])
n7

array([[1, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [30]:
n7[1]

array([3, 3, 3])

In [31]:
n7[:,2]

array([2, 3, 4])

In [32]:
n7[2,:]

array([4, 4, 4])

In [33]:
n7[0,1]

np.int64(2)

In [34]:
n7.transpose()

array([[1, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [35]:
import pandas as pd

In [36]:
s1=pd.Series([2,4,6])
s1
type(s1)

pandas.core.series.Series

In [37]:
s1

0    2
1    4
2    6
dtype: int64

In [40]:
s1 = pd.Series([3,5,5], index= ['a','b','c'])
s1

a    3
b    5
c    5
dtype: int64

In [41]:
s1 = pd.Series({'a':3,'b':5,'c':8})
s1

a    3
b    5
c    8
dtype: int64

In [42]:
s1+5

a     8
b    10
c    13
dtype: int64

In [43]:
s1+s1

a     6
b    10
c    16
dtype: int64

In [46]:
iris = pd.read_csv("/Users/menatalla/Downloads/iris.csv")

In [48]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [53]:
iris.min()

Sepal.Length       4.3
Sepal.Width        2.0
Petal.Length       1.0
Petal.Width        0.1
Species         setosa
dtype: object

In [50]:
iris.mode()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
0           5.0          3.0           1.4          0.2      setosa
1           NaN          NaN           1.5          NaN  versicolor
2           NaN          NaN           NaN          NaN   virginica

In [54]:
iris.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

In [55]:
def half(s):
    return s*0.5

In [56]:
iris[['Sepal.Length','Sepal.Width']].apply(half)

Sepal.Length  Sepal.Width
0            2.55         1.75
1            2.45         1.50
2            2.35         1.60
3            2.30         1.55
4            2.50         1.80
..            ...          ...
145          3.35         1.50
146          3.15         1.25
147          3.25         1.50
148          3.10         1.70
149          2.95         1.50

[150 rows x 2 columns]

In [57]:
iris['Species'].value_counts()

Species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [58]:
iris.sort_values(by='Sepal.Length')

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [59]:
pd.DataFrame({'names':['a','b','c'], 'values':[1,2,3]})

names  values
0     a       1
1     b       2
2     c       3

In [ ]:
iris.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [61]:
iris.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [63]:
iris.shape

(150, 5)

In [64]:
iris.iloc[0:5,0:3]

Sepal.Length  Sepal.Width  Petal.Length
0           5.1          3.5           1.4
1           4.9          3.0           1.4
2           4.7          3.2           1.3
3           4.6          3.1           1.5
4           5.0          3.6           1.4

In [65]:
iris.drop('Species',axis=1)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [68]:
iris.drop([1,5,7],axis=0)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          3.5           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
6             4.6          3.4           1.4          0.3     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [69]:
df1= pd.DataFrame({
    'emp_id': ['101','102','103','104'],
    'dept': ['hr','admin','hr','admin'],
    'gender': ['m','f','m','f'],
    'salary': [1000,1500,2000,1200]
})

In [70]:
df2=pd.DataFrame({
    'emp_id': ['105','106','107','108'],
    'location': ['delhi','mumbai','delhi','mumbai'],
    'distance': [10,15,20,25],
    'salary': [1000,1500,2000,1200]
})

In [71]:
df1

emp_id   dept gender  salary
0    101     hr      m    1000
1    102  admin      f    1500
2    103     hr      m    2000
3    104  admin      f    1200

In [72]:
df2

emp_id location  distance  salary
0    105    delhi        10    1000
1    106   mumbai        15    1500
2    107    delhi        20    2000
3    108   mumbai        25    1200

In [73]:
pd.concat([df1,df2], axis=0, sort=False)

emp_id   dept gender  salary location  distance
0    101     hr      m    1000      NaN       NaN
1    102  admin      f    1500      NaN       NaN
2    103     hr      m    2000      NaN       NaN
3    104  admin      f    1200      NaN       NaN
0    105    NaN    NaN    1000    delhi      10.0
1    106    NaN    NaN    1500   mumbai      15.0
2    107    NaN    NaN    2000    delhi      20.0
3    108    NaN    NaN    1200   mumbai      25.0

In [75]:
pd.concat([df1,df2], axis=0, sort=True)

dept  distance emp_id gender location  salary
0     hr       NaN    101      m      NaN    1000
1  admin       NaN    102      f      NaN    1500
2     hr       NaN    103      m      NaN    2000
3  admin       NaN    104      f      NaN    1200
0    NaN      10.0    105    NaN    delhi    1000
1    NaN      15.0    106    NaN   mumbai    1500
2    NaN      20.0    107    NaN    delhi    2000
3    NaN      25.0    108    NaN   mumbai    1200

In [76]:
pd.concat([df1,df2], axis=1, sort=False)

emp_id   dept gender  salary emp_id location  distance  salary
0    101     hr      m    1000    105    delhi        10    1000
1    102  admin      f    1500    106   mumbai        15    1500
2    103     hr      m    2000    107    delhi        20    2000
3    104  admin      f    1200    108   mumbai        25    1200

In [81]:
pd.merge(df1,df2, how='outer', on='salary')

emp_id_x   dept gender  salary emp_id_y location  distance
0      101     hr      m    1000      105    delhi        10
1      104  admin      f    1200      108   mumbai        25
2      102  admin      f    1500      106   mumbai        15
3      103     hr      m    2000      107    delhi        20