In [8]:
import numpy as np
n1 = np.array([1,2,3,8,9,10])
n2 = np.array([4,5,6,8,9,10])


In [9]:
np.vstack((n1,n2))

array([[ 1,  2,  3,  8,  9, 10],
       [ 4,  5,  6,  8,  9, 10]])

In [10]:
np.hstack((n1,n2))

array([ 1,  2,  3,  8,  9, 10,  4,  5,  6,  8,  9, 10])

In [11]:
np.column_stack((n1,n2))

array([[ 1,  4],
       [ 2,  5],
       [ 3,  6],
       [ 8,  8],
       [ 9,  9],
       [10, 10]])

In [12]:
np.intersect1d(n1,n2)

array([ 8,  9, 10])

In [13]:
np.setdiff1d(n1,n2)

array([1, 2, 3])

In [14]:
np.setdiff1d(n2,n1)

array([4, 5, 6])

In [15]:
np.sum([n1,n2])

np.int64(75)

In [16]:
np.sum([n1,n2],axis=0)

array([ 5,  7,  9, 16, 18, 20])

In [17]:
np.sum([n1,n2],axis=1)

array([33, 42])

In [18]:
n1=n1+1

In [19]:
print(n1)

[ 2  3  4  9 10 11]


In [20]:
n1

array([ 2,  3,  4,  9, 10, 11])

In [21]:
n1=n1/4

In [22]:
n1

array([0.5 , 0.75, 1.  , 2.25, 2.5 , 2.75])

In [23]:
n1=n1*100
n1

array([ 50.,  75., 100., 225., 250., 275.])

In [26]:
np.mean(n1)


np.float64(162.5)

In [27]:
np.median(n1)


np.float64(162.5)

In [28]:
np.std(n1)

np.float64(89.8494110535326)

In [29]:
np.save("my_numpyarray",n1)

In [30]:
n3=np.load("my_numpyarray.npy")
n3

array([ 50.,  75., 100., 225., 250., 275.])

In [31]:
n1+n2

array([ 54.,  80., 106., 233., 259., 285.])

In [32]:
n1.shape

(6,)

In [33]:
n2.shape

(6,)

In [35]:
n5=np.array([1,2,3])
n5.shape=(1,3)
n5

array([[1, 2, 3]])

In [36]:
n6=np.array([2,4,6])
n6.shape=(3,1)
n6

array([[2],
       [4],
       [6]])

In [37]:
n5+n6

array([[3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [38]:
n7=np.array([[1,2,2],[3,3,3],[4,4,4]])
n7

array([[1, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [39]:
n7[1]

array([3, 3, 3])

In [40]:
n7[:,2]

array([2, 3, 4])

In [41]:
n7[2,:]

array([4, 4, 4])

In [42]:
n7[0,1]

np.int64(2)

In [43]:
n7.transpose()

array([[1, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])