In [9]:
n1 = np.array([1,2,3,8,9,10])
n2 = np.array([4,5,6,8,9,10])


In [2]:
import numpy as np

In [4]:
np.vstack((n1,n2))

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6])

In [8]:
np.column_stack((n1,n2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
np.intersect1d(n1,n2)

array([ 8,  9, 10])

In [11]:
np.setdiff1d(n1,n2)

array([1, 2, 3])

In [12]:
np.setdiff1d(n2,n1)

array([4, 5, 6])

In [13]:
np.sum([n1,n2])

np.int64(75)

In [14]:
np.sum([n1,n2],axis=0)

array([ 5,  7,  9, 16, 18, 20])

In [15]:
np.sum([n1,n2],axis=1)

array([33, 42])